//! Coaching event types and the tip structures that flow through the pipeline.
#![allow(dead_code)]

/// A coaching event detected by the rules engine.
///
/// Each variant carries the raw numeric facts — no prose yet.
/// Prose is generated by `Analyzer` into a `StructuredTip.fact` string,
/// which the `Rephraser` then varies for the driver.
#[derive(Debug, Clone)]
pub enum CoachEvent {
    // ── Braking ─────────────────────────────────────────────────────────────
    /// Driver braked earlier than their reference lap at this corner.
    BrakingTooEarly {
        corner_id: u8,
        /// Fraction of track length (0.0–1.0) braked earlier than reference.
        delta_track_pos: f32,
    },
    /// Driver carried too much entry speed into the corner.
    BrakingTooLate {
        corner_id: u8,
        entry_speed_delta_kph: f32,
    },
    /// Too many ABS activations through the braking zone — over-pressure.
    ExcessiveBrakePressure { corner_id: u8, abs_count: u32 },
    /// Brake released too abruptly before apex — should trail off gradually.
    TrailBrakeTooSudden { corner_id: u8 },

    // ── Corner ───────────────────────────────────────────────────────────────
    /// Apex speed lower than reference — time being lost mid-corner.
    SlowApex { corner_id: u8, delta_kph: f32 },
    /// Apex speed faster than reference — positive feedback.
    ImprovedApexSpeed { corner_id: u8, delta_kph: f32 },
    /// Brake still applied at or past the geometric apex, preventing rotation.
    BrakeOverApex { corner_id: u8 },
    /// Driver's minimum speed occurs significantly before the geometric apex.
    EarlyApex { corner_id: u8, early_m: f32 },
    /// Driver's closest approach to the geometric apex deviates from the ideal line.
    MissedApex { corner_id: u8, deviation_m: f32 },

    // ── Exit ─────────────────────────────────────────────────────────────────
    /// Throttle applied before car is rotated — TC being triggered.
    ThrottleTooEarly { corner_id: u8 },
    /// Throttle applied later than reference — exit speed being left behind.
    ThrottleTooLate { corner_id: u8, delta_track_pos: f32 },
    /// Throttle increases too slowly after the apex.
    ThrottleBuildupSlow { corner_id: u8 },
    /// Throttle stays at partial application before committing.
    ThrottleHesitation { corner_id: u8 },
    /// High steering angle at throttle application — car pointing wrong way.
    ExitUndersteer { corner_id: u8 },

    // ── Mechanical ───────────────────────────────────────────────────────────
    /// Driver in a different gear than reference at the apex.
    WrongGearAtApex {
        corner_id: u8,
        actual_gear: i32,
        ref_gear: i32,
    },

    // ── Macro ────────────────────────────────────────────────────────────────
    /// No throttle, no brake for too long at racing speed.
    CoastingExcessive { duration_ms: u32, speed_kph: f32 },
    /// Both pedals active simultaneously (not a blip).
    ThrottleBrakeOverlap { overlap_ms: u32 },
    /// High-frequency steering reversals — nervous / sawing inputs.
    SteeringSaw { reversals_per_sec: f32 },

    // ── Positive ─────────────────────────────────────────────────────────────
    /// Consistent brake point across multiple laps — reinforce.
    ConsistentBrakePoint { corner_id: u8 },
}

/// A coaching event paired with a plain-English fact string and metadata.
#[derive(Debug, Clone)]
pub struct StructuredTip {
    pub event: CoachEvent,
    /// Short, actionable coaching sentence ready for display and TTS.
    pub fact: String,
    /// Priority 1 (low / positive) – 5 (critical). Higher tips displace lower ones.
    pub priority: u8,
    /// Corner ID this relates to, if corner-specific.
    pub corner_id: Option<u8>,
    /// Estimated time lost vs reference in this corner (seconds).
    /// `None` when a reference lap is unavailable or the loss is negligible.
    pub time_lost_s: Option<f32>,
}

impl StructuredTip {
    pub fn new(
        event: CoachEvent,
        fact: impl Into<String>,
        priority: u8,
        corner_id: Option<u8>,
    ) -> Self {
        Self {
            event,
            fact: fact.into(),
            priority,
            corner_id,
            time_lost_s: None,
        }
    }

    /// Attach an estimated time loss to this tip.
    pub fn with_time_loss(mut self, loss_s: Option<f32>) -> Self {
        self.time_lost_s = loss_s.filter(|&s| s > 0.02);
        self
    }
}

/// A tip ready for display and TTS output.
///
/// This is the final form that flows from the coach thread to the UI.
#[derive(Debug, Clone)]
pub struct CoachTip {
    /// The spoken / displayed text.
    pub text: String,
    /// Corner this relates to, if any.
    pub corner_id: Option<u8>,
    /// 1–5, matching the source `StructuredTip`.
    pub priority: u8,
    /// Estimated time lost in this corner vs reference. `None` if unavailable.
    pub time_lost_s: Option<f32>,
    pub generated_at: std::time::Instant,
}
