//! Coaching event types and the tip structures that flow through the pipeline.
#![allow(dead_code)]

/// A coaching event detected by the rules engine.
///
/// Each variant carries the raw numeric facts — no prose yet.
/// Prose is generated by `Analyzer` into a `StructuredTip.fact` string,
/// which the `Rephraser` then varies for the driver.
#[derive(Debug, Clone)]
pub enum CoachEvent {
    // ── Braking ─────────────────────────────────────────────────────────────
    /// Driver braked earlier than their reference lap at this corner.
    BrakingTooEarly {
        corner_id: u8,
        /// Fraction of track length (0.0–1.0) braked earlier than reference.
        delta_track_pos: f32,
        /// Rough time estimate in milliseconds.
        estimated_time_lost_ms: f32,
    },
    /// Driver carried too much entry speed into the corner.
    BrakingTooLate {
        corner_id: u8,
        entry_speed_delta_kph: f32,
    },
    /// Brake application point varies significantly between laps.
    InconsistentBrakePoint {
        corner_id: u8,
        /// Standard deviation of brake point across recent laps.
        std_dev_track_pos: f32,
    },
    /// ABS activating more than expected — too much pressure.
    AbsAbuse {
        count: u32,
        window_secs: f32,
    },
    /// Brake released too abruptly before apex — trail brake dropped.
    TrailBrakeTooShort {
        corner_id: u8,
    },

    // ── Corner ───────────────────────────────────────────────────────────────
    /// Apex speed lower than reference — time being lost mid-corner.
    SlowApex {
        corner_id: u8,
        delta_kph: f32,
    },
    /// Apex speed faster than reference — positive feedback.
    ImprovedApexSpeed {
        corner_id: u8,
        delta_kph: f32,
    },
    /// Brake still active deep in corner — entry understeer.
    EntryUndersteer {
        corner_id: u8,
    },
    /// Steering reversal detected mid-corner — overdriving entry.
    MidCornerCorrection {
        corner_id: u8,
    },

    // ── Exit ─────────────────────────────────────────────────────────────────
    /// Throttle applied before car is rotated — TC being triggered.
    ThrottleTooEarly {
        corner_id: u8,
    },
    /// Throttle applied later than reference — exit speed being left behind.
    ThrottleTooLate {
        corner_id: u8,
        delta_track_pos: f32,
    },
    /// TC activating more than expected — throttle too aggressive or early.
    TcAbuse {
        count: u32,
        window_secs: f32,
    },

    // ── Macro ────────────────────────────────────────────────────────────────
    /// No throttle, no brake for too long at racing speed.
    CoastingExcessive {
        duration_ms: u32,
        speed_kph: f32,
    },
    /// Both pedals active simultaneously (not a blip).
    ThrottleBrakeOverlap {
        overlap_ms: u32,
    },
    /// High-frequency steering reversals — nervous / sawing inputs.
    SteeringSaw {
        reversals_per_sec: f32,
    },

    // ── Positive ─────────────────────────────────────────────────────────────
    /// Consistent brake point across multiple laps — reinforce.
    ConsistentBrakePoint {
        corner_id: u8,
    },
}

/// A coaching event paired with a plain-English fact string and metadata.
///
/// The `fact` field is a complete, factual sentence — e.g.
/// "Corner 3: you're braking 12% of the track earlier than your reference."
/// The `Rephraser` may reword this for variety while preserving the meaning.
#[derive(Debug, Clone)]
pub struct StructuredTip {
    pub event: CoachEvent,
    /// Plain-English description of the observed issue.
    pub fact: String,
    /// Priority 1 (low / positive) – 5 (critical). Higher tips displace lower ones.
    pub priority: u8,
    /// Corner ID this relates to, if corner-specific.
    pub corner_id: Option<u8>,
}

impl StructuredTip {
    pub fn new(
        event: CoachEvent,
        fact: impl Into<String>,
        priority: u8,
        corner_id: Option<u8>,
    ) -> Self {
        Self {
            event,
            fact: fact.into(),
            priority,
            corner_id,
        }
    }
}

/// A tip ready for display and TTS output.
///
/// This is the final form that flows from the coach thread to the UI.
/// The `text` may have been rephrased by the `Rephraser`.
#[derive(Debug, Clone)]
pub struct CoachTip {
    /// The spoken / displayed text.
    pub text: String,
    /// Corner this relates to, if any.
    pub corner_id: Option<u8>,
    /// 1–5, matching the source `StructuredTip`.
    pub priority: u8,
    pub generated_at: std::time::Instant,
}
